region: EU
app: 
  key: 
    name: EdgeMultiplay
    version: 1.3
    organization: MobiledgeX-Samples
  image_path: docker.mobiledgex.net/mobiledgex-samples/images/edge-multiplay
  image_type: 1
  deployment: docker
  default_flavor: 
    name: m4.small
  access_ports: "tcp:3000,tcp:7776,udp:5000"
