name: Publish to MobiledgeX Registry & Deploy app

on:
  push
    

jobs:
 push_to_registry:
    name:  Publish to MobiledgeX Registry & Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: check-out-repo
        uses: actions/checkout@v2

      - name: Push Image to MobiledgeX Docker Registery (Gitlab)
        id: mobiledgex-registery
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.MOBILEDGEX_SAMPLES_USERNAME }}
          password: ${{ secrets.MOBILEDGEX_SAMPLES_PASSWORD }}
          registry: docker.mobiledgex.net
          repository: mobiledgex-samples/images/edge-multiplay-test
          tags: 1.2
